# Generated by Django 3.0.6 on 2020-05-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='firstname',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='lastname',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='location_country',
        ),
    ]
