# Generated by Django 3.0.6 on 2020-05-31 15:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200529_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.CharField(default='Client', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location_country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
