# Generated by Django 3.0.6 on 2020-05-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200531_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='profile_summary',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='title',
            field=models.TextField(default='Developer', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(max_length=2000, upload_to='media/'),
        ),
    ]
