# Generated by Django 3.0 on 2020-05-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Job')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Skill')),
            ],
        ),
    ]
