# Generated by Django 3.0 on 2020-05-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_certificate_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerskill',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile'),
            preserve_default=False,
        ),
    ]
