# Generated by Django 3.0 on 2020-05-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_freelancerpayment_payment_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobproposal',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobproposal',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.UserProfile'),
            preserve_default=False,
        ),
    ]
