# Generated by Django 3.0 on 2020-05-21 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200521_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='skill_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.SkillCategory'),
            preserve_default=False,
        ),
    ]
