# Generated by Django 3.0 on 2020-05-21 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_skill_skill_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='job_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Job'),
            preserve_default=False,
        ),
    ]
